spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.1.75:1521/orcl
    data-username: root
    data-password: admin123
#    data-username: scott
#    data-password: Admin123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/oa?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: admin123
      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:oracle:thin:@192.168.1.75:1521/orcl
#      username: scott
#      password: Admin123
#      driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    root: info
    cn.saberking: debug
  file:
    name: logs/blog-dev.log



